### ISSUE TITLE
'POST /files/signedUrl/' 에서 folder

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-auth#4]
@june2 
문서에 따르면 POST로 보내는 data가 아래와 같은데 'folder'는 사용이 안되고 있는 거 같네요?
response로 오는 결과에 'folder'는 반영이 안되서 오는 듯 합니다.

{
  "folder": "string",
  "name": "string",
  "type": "string"
}

**Comment by june2** [comment]
- 네, 지금은  folder 적용안됫어요. (현재 not required 에요)
- 폴더값을 보내면 아래처럼 key에 적용할 예정입니다.
```
{
  "uploadURL": "https://s3.~~~",
  "key": "folder/1583937416003.jpg"
}
```

**Comment by dustnote** [comment]
@june2 
추가 질문 하나.
만약 Donee가 업로드하는 파일 중, 공개되면 민감할지도 모르는 사업자등록증 사본이나 통장사본 등에 대한 권한을 해당 Donee와 Admin만 볼 수 있게 할 수 있을까요?

**Comment by june2** [comment]
네, 지금  s3를 테스트 용으로 전부 퍼블릭으로 해놓았는데,  s3 폴더별 접근 제어  설정할수 있어요.
