### ISSUE TITLE
PresignedURL 받아서 PUT할 때CORS 에러 발생

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-auth#5]
@june2 
'POST /files/signedUrl'로 uploadURL을 받아서 그 URL로 PUT 시도하면 CORS 에러가 발생합니다.

**Comment by june2** [comment]
- https://s3.ap-northeast-2.amazonaws.com/tipj.ar/upload.html
- 요청이 잘못간거같은데요. 위에 데모페이지 만들어놧는데 저기 sample확인해주세요.

**Comment by dustnote** [comment]
@june2 
http://localhost에서 하면 CORS 발생합니다.

**Comment by dustnote** [comment]
@june2 
CORS 해결된 듯하네요.
