### ISSUE TITLE
'POST /donees/'에서 필수 항목.

### ISSUE THREAD

**Issue by dustnote** [ESC2020/tipjar-auth#9]
@june2 
donee 등록할 때 필수 항목이 어떤 것들로 설정되어 있나요?
{
  "thumbnail_path": "string",
  "upload_file_path": "string",
  "name": "string",
  "description": "string",
  "bussiness_number": "string"
}

name 만 필수면 될 것 같습니다.
아바타는 없으면 기본 이미지 보여주고, 설명은 입력하지 않아도 되고,
사업자번호랑 사본이미지는 없어도 되지만, 정산을 요청하려면 입력해야하는 것으로 하면 좋을 것 같습니다.

**Comment by june2** [comment]
수정 완료!
